version: '3.8'

services:
  api:
    image: ghcr.io/kuasar-mknd/archioweb-api:latest
    container_name: archioweb-api
    restart: unless-stopped
    ports:
      - "3000:3000" # API
      - "3001:3001" # WebSocket
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://mongo:27017/homeGarden
      # JWT_SECRET should be defined in Portainer Environment variables for security
      - JWT_SECRET=${JWT_SECRET} 
    networks:
      - backend
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: archioweb-mongo
    restart: unless-stopped
    # No ports exposed to host = Ultra Security (Only accessible via backend network)
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongo-data:
